-- 添加设备表的新字段
ALTER TABLE devices
    ADD COLUMN IF NOT EXISTS network_cards TEXT,
    ADD COLUMN IF NOT EXISTS display_card VARCHAR(191),
    ADD COLUMN IF NOT EXISTS resolution VARCHAR(50),
    ADD COLUMN IF NOT EXISTS timezone VARCHAR(50),
    ADD COLUMN IF NOT EXISTS language VARCHAR(50),
    ADD COLUMN IF NOT EXISTS block_reason TEXT,
    ADD COLUMN IF NOT EXISTS block_time TIMESTAMP NULL,
    ADD COLUMN IF NOT EXISTS unblock_time TIMESTAMP NULL,
    ADD COLUMN IF NOT EXISTS last_alert_time TIMESTAMP NULL,
    ADD COLUMN IF NOT EXISTS alert_count INT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS heartbeat_rate INT DEFAULT 60,
    ADD COLUMN IF NOT EXISTS last_heartbeat TIMESTAMP NULL,
    ADD COLUMN IF NOT EXISTS average_usage_time BIGINT,
    ADD COLUMN IF NOT EXISTS peak_usage_time BIGINT,
    ADD COLUMN IF NOT EXISTS last_active_date TIMESTAMP NULL;
